version: "3"
services:
  fullnode:
    image: "coti/fullnode:${VERSION}"
    build:
      context: .
      args:
        MODULE: "fullnode"
        VERSION: "${VERSION}"
    ports:
      - "7070:7070"
    volumes:
      - "./configs:/app/configs"
    restart: on-failure
    command: ["java", "-jar", "fullnode/target/fullnode-${VERSION}.jar", "--spring.config.additional-location=./configs/fullnode1.properties"]

